

#ifndef _ENUMDEFS_H_INCLUDED_
#define _ENUMDEFS_H_INCLUDED_

#define MARKER_LENGTH 110;

typedef enum  
{
    NOT_QUALIFIED ,
    QUALIFIED_4_X ,
    MARGIN_CALL_2_XD,
    MARGIN_CALL_1_XD,
    MIN_EQUITY_CALL_1_XK,
    QUALIFIED_RESTRICTION,
    CASH_ONLY
}EDayTraderStatus;

typedef enum 
{
    CALL,
    PUT
}ECallPut;

typedef enum  
{
	OPTN = 100,
	EQ,
	FI,
	MF,
	BOND,
	INDX,
	ADP,
	TWO
}EAccountConstants;


typedef enum 
{
	LONG_TYPE,
	SHORT_TYPE
}ELongOrShort;

typedef enum 
{
	MARGINABLE,
	NOT_MARGINABLE
}EMarginable;

typedef enum 
{
	MARGIN_ACCOUNT,
	CASH_ACCOUNT,
	PM_ACCOUNT
}EAccountType;

typedef enum 
{
	MARGIN,
	CASH,
	PM
}EMarginLevel;

typedef enum 
{
	LEVEL_1,
	LEVEL_2,
	LEVEL_3,
	LEVEL_4
}EOptionLevel;

typedef enum 
{
	ACCOUNTS,
	TRADING
}EAlertCategory;

typedef enum 
{
	UNREAD,
	READ
}EAlertReadFlag;

typedef enum 
{
	GROUPTYPE_DEPOSITS,
	GROUPTYPE_WITHDRAWALS,
	GROUPTYPE_TRADES,
	GROUPTYPE_CASH,
	GROUPTYPE_CURRENCY_EXCHANGE,
	GROUPTYPE_SWEEP,
	GROUPTYPE_CORPORATE_ACTIONS
}EGroupType;

typedef enum
{
	ASSETTYPE_ALL,
	ASSETTYPE_EQ,
	ASSETTYPE_OP,
	ASSETTYPE_MMF,
	ASSETTYPE_MF,
	ASSETTYPE_BONDS,
	ASSETTYPE_ASSIGNMENTS,
	ASSETTYPE_EXERCISE,
	ASSETTYPE_EXPIRATION
}EAssetType;

typedef enum 
{
	TRANSTYPE_ASSIGNMENT,
	TRANSTYPE_CHECK,
	TRANSTYPE_CONTRIBUTION,
	TRANSTYPE_CORPORATE_ACTIONS,
	TRANSTYPE_CURRENCY_XCH,
	TRANSTYPE_DEPOSIT,
	TRANSTYPE_DIRECT_DEBIT,
	TRANSTYPE_DIRECT_DEPOSIT,
	TRANSTYPE_DISTRIBUTION,
	TRANSTYPE_DIVIDEND,
	TRANSTYPE_EXERCISE,
	TRANSTYPE_EXPIRATION,
	TRANSTYPE_FEE,
	TRANSTYPE_INTEREST,
	TRANSTYPE_POS,
	TRANSTYPE_SWEEP,
	TRANSTYPE_TRANSFER,
	TRANSTYPE_WIRE,
	TRANSTYPE_ALL, 
	
	TRANSTYPE_BOUGHT,
	TRANSTYPE_SOLD,
	TRANSTYPE_SOLD_SHORT,
	TRANSTYPE_BOUGHT_TO_COVER,
	TRANSTYPE_BOUGHT_TO_OPEN,
	TRANSTYPE_SOLD_TO_CLOSE,
	TRANSTYPE_EXCHANGE,
	TRANSTYPE_CANCEL_SOLD,
	TRANSTYPE_CANCEL_BOUGHT,
	TRANSTYPE_OPTION_EXPIRATION,
	TRANSTYPE_OPTION_EXERCISE,
	TRANSTYPE_OPTION_ASSIGNMENT,
}ETransType;
	
#endif//_ENUMDEFS_H_INCLUDED_
